# permissions for end users to view virtualmachineinstancerescues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualmachineinstancerescue-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vmrescuer
    app.kubernetes.io/part-of: vmrescuer
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachineinstancerescue-viewer-role
rules:
- apiGroups:
  - monitor.hitosea.com
  resources:
  - virtualmachineinstancerescues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.hitosea.com
  resources:
  - virtualmachineinstancerescues/status
  verbs:
  - get
