# permissions for end users to edit virtualmachinemigrations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualmachinemigration-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: vmrescuer
    app.kubernetes.io/part-of: vmrescuer
    app.kubernetes.io/managed-by: kustomize
  name: virtualmachinemigration-editor-role
rules:
- apiGroups:
  - monitor.hitosea.com
  resources:
  - virtualmachinemigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitor.hitosea.com
  resources:
  - virtualmachinemigrations/status
  verbs:
  - get
