apiVersion: monitor.hitosea.com/v1
kind: VirtualMachineNodeWatcher
metadata:
  labels:
    app.kubernetes.io/name: virtualmachinenodewatcher
    app.kubernetes.io/instance: virtualmachinenodewatcher-sample
    app.kubernetes.io/part-of: vmrescuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: vmrescuer
  name: virtualmachinenodewatcher-sample
spec:
  interval: 3m
  enable: true
